#! /bin/sh

bspwmdir="$HOME/.config/bspwm"
polybardir="$HOME/.config/bspwm/rices/$RICEUSED/polybar"

function launch() {
	local running
	running="$(pidof "$1")"
	[ "$running" ] && kill -9 $(pidof $1)
	eval "$* &"
}

function SetBswpmColor() {
	bspc config normal_border_color		"$1"
	bspc config active_border_color		"$2"
	bspc config focused_border_color	"$3"
}

function SetMyRice() {
	case $RICEUSED in
		fuchsia)
			SetBswpmColor "#ff0080" "#ff0080" "#ff0080"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;
		
		red)
			SetBswpmColor "#ff0000" "#ff0000" "#ff0000"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		blue)
			SetBswpmColor "#0000ff" "#0000ff" "#0000ff"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		white)
			SetBswpmColor "#ffffff" "#ffffff" "#ffffff"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		green)
			SetBswpmColor "#00ff00" "#00ff00" "#00ff00"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		yellow)
			SetBswpmColor "#ffff00" "#ffff00" "#ffff00"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		cian)
			SetBswpmColor "#00ffff" "#00ffff" "#00ffff"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

		purple)
			SetBswpmColor "#ff00ff" "#ff00ff" "#ff00ff"
			launch polybar -q main -c ${polybardir}/config.ini &
			;;

	esac
}

function StartApps() {
	launch sxhkd -c ${bspwmdir}/sxhkdrc &
	launch picom --config ${bspwmdir}/rices/$RICEUSED/picom.conf &
	launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	nitrogen --restore &
	xsetroot -cursor_name left_ptr
	dunst &
}