#! /bin/sh

dir="$HOME/.config/bspwm"
rofi_command="rofi -theme $HOME/.config/bspwm/scripts/RiceSelector.rasi"

fuchsia="Fuchsia"
red="Red"
blue="Blue"
white="White"
green="Green"
yellow="Yellow"
cian="Cian"
purple="Purple"

options="$fuchsia\n$red\n$blue\n$white\n$green\n$yellow\n$cian\n$purple"
chosen="$(printf "$options" | $rofi_command -dmenu)"
	case $chosen in
		
		$fuchsia)
			cat <<< "fuchsia" > $dir/rice.cfg
			bspc wm -r
			;;

		$red)
			cat <<< "red" > $dir/rice.cfg
			bspc wm -r
			;;

		$blue)
			cat <<< "blue" > $dir/rice.cfg
			bspc wm -r
			;;

		$white)
			cat <<< "white" > $dir/rice.cfg
			bspc wm -r
			;;

		$green)
			cat <<< "green" > $dir/rice.cfg
			bspc wm -r
			;;

		$yellow)
			cat <<< "yellow" > $dir/rice.cfg
			bspc wm -r
			;;

		$cian)
			cat <<< "cian" > $dir/rice.cfg
			bspc wm -r
			;;

		$purple)
			cat <<< "purple" > $dir/rice.cfg
			bspc wm -r
			;;
	esac